### ISSUE TITLE
models total_features_namelist.txt is missing when using mirRge in 'Predict' mode (following conda installation instructions)

### ISSUE THREAD

**Issue by simon-ty** [mhalushka/miRge#10]
Hi miRge development team,

My Institute have a new installation of miRge2.0, which followed the installation using Bioconda.  We found a missing file when trying to use 'Predict' mode:

line 647, in main
    preprocess_featureFiles(fileToPredict, os.path.join(modelDir, 'total_features_namelist.txt'))
  File "miniconda/envs/mirge2/lib/python2.7/site-packages/mirge/utils/preprocess_featureFiles.py", line 49, in preprocess_featureFiles
    with open(feature_namelist_file, 'r') as inf:
IOError: [Errno 2] No such file or directory: 'miniconda/envs/mirge2/lib/python2.7/site-packages/mirge/models/total_features_namelist.txt'

I solved it by cloning from GitHub and copying over the 'models' directory to our installation path for mirge.  Can you see any issue with fixing it in this way?  Please also update your installation instructions/code to fix this for those future users who use Bioconda to install miRge2.0.  Thanks and best regards
Simon Yin

**Comment by mhalushka** [comment]
Simon - Thank you for catching that bug.  We will start working to get it corrected.

**Comment by sarawernig** [comment]
I have the same issue. I have installed miRge a week ago, following **pip installation** instructions. The tool works normally in annotation mode but fails with the same error in predict mode. 

`Performing quantitation analysis of H3K27ac_IP_smallRNA_rep1_S2_R1_001_trimmed2.fastq...
It takes: 88.26s

Performing annotation for all of the collasped sequences...
All annotation cycles completed (157.69 sec).

Summarizing and tabulating results...
Summary Complete (40.18 sec)
Annotation of miRge2.0 Completed (286.13 sec)

Performing prediction of novel miRNAs...
Start to predict
Traceback (most recent call last):
  File "/usr/local/bin/miRge2.0", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/mirge/__main__.py", line 647, in main
    preprocess_featureFiles(fileToPredict, os.path.join(modelDir, 'total_features_namelist.txt'))
  File "/usr/local/lib/python2.7/site-packages/mirge/utils/preprocess_featureFiles.py", line 49, in preprocess_featureFiles
    with open(feature_namelist_file, 'r') as inf:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/mirge/models/total_features_namelist.txt'`

**Comment by mhalushka** [comment]
Ugh. Sorry.  The post-doc who is coming to take over the project has been delayed in coming and the former post-doc isn't fixing his errors.  You may want to try the Bioconda install and see if that gets the files properly installed.  One other group who had errors with the pip install got everything to work for their needs with the Bioconda install.
