### ISSUE TITLE
No miRNA were found in sample

### ISSUE THREAD

**Issue by mszabo92** [mhalushka/miRge#17]
Hi!
I tried to use miRge2.0 for microRNA sequencing data analysis. I used the command below and the following message came up:
`miRge2.0 annotate -s /path/to/input_file.fastq -d miRBase -pb /path/to/bowtie -lib /path/to/miRge.Libs -sp rat -ad illumina`
> ...
> Summarizing and tabulating results...
> No miRNA reads were found in sample input_file.fastq. Please check your files and provided arguments.

Actually I'm quiet new in RNA-seq data analysis, therefore I tried the predict mode as well, but I got the same output. 
Here is my command for the predict mode:
`
miRge2.0 predict -s /path/to/input_file.fastq -d miRBase -pb /path/to/bowtie -lib /path/to/miRge.Libs -ps /path/to/samtools -pr /path/to/rnafold -sp rat -ad illumina`

**Comment by mhalushka** [comment]
It likely suggests there were no mature miRNAs in your sample.  Is your sample standard RNA-seq or small RNA RNA-seq?  If standard, that would explain it.  If small RNA, then it might be something else.  The first thing to do is a grep search for a common miRNA in your fasta file such as $grep 'TAGCTTATCAGACTGATGTTGA'  input_file.fastq.  If it returns nothing, you have no miRNAs. If it returns reads, then see what sequence comes after (and before) the miRNA.  If there is sequence in front of the miRNA, you might need to use cutadapt standalone to remove it before running miRge.  If there is sequence after it then you want to make sure it matched the illumina adaptors or type in the sequence after -ad.  Let me know if that helps.

**Comment by mszabo92** [comment]
Thanks your quick reply and advices!
Small RNA-seq was performed on my samples. 
I ran the `$grep 'TAGCTTATCAGACTGATGTTGA' ` command, as you mentioned, a tons of sequences were listed with adapter sequences at the 3' end/after the sequence.  Still I typed one of the sequences after  `-ad` I got the same output as before. 
See the whole generated ouput below. I see some errors, maybe that can explain my problem.

>  miRge2.0 annotate -s /home/biochem-ubu/mirdeep2/src/H28_trim.fastq -d miRBase -pb /home/biochem-ubu/anaconda3/bin/ -lib /home/biochem-ubu/ -sp rat -ad AGATCGGAAGAGCA
> Performing quantitation analysis of H28.fastq...
> Process Worker-2:
> Traceback (most recent call last):
>   File "/home/biochem-ubu/anaconda3/envs/my_env/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
>     self.run()
>   File "/home/biochem-ubu/anaconda3/envs/my_env/lib/python2.7/site-packages/mirge/utils/trim_file.py", line 54, in run
>     read = modifier(read)
> TypeError: __call__() takes exactly 3 arguments (2 given)
> Traceback (most recent call last):
>   File "/home/biochem-ubu/anaconda3/envs/my_env/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
>     send(obj)
> IOError: [Errno 32] Broken pipe
> It takes: 3.20s
> 
> Performing annotation for all of the collasped sequences...
> All annotation cycles completed (0.48 sec).
> 
> Summarizing and tabulating results...
> No miRNA reads were found in sample H28.fastq. Please check your files and provided arguments.

**Comment by mhalushka** [comment]
Yes. You are using too recent a version of Cutadapt that miRge is not yet compatible with.  You need an earlier version.  See this note:
PLEASE NOTE: miRge2.0 is currently incompatible with cutadapt v1.18. Using v1.18 will give a "TypeError: call() takes exactly 3 arguments (2 given)" error.
We use cutadapt v1.16.  If you install that version it will work fine.  Thank you for the explanation of what has happened.

**Comment by mszabo92** [comment]
Oh, I see, that just escaped my attention. Now it's working properly, thank you!
However I would like to note some minor observation that could be helpful. I refreshed cutadapt to version 1.16, but an error message came up  `
> ...
The 'cutadapt>=1.11' distribution was not found and is required by mirge`

Then I refreshed for that version and it worked. Also I had some deal with the adapters, while if I defined adapter as `-ad illumina` it gave zero hit. But after I checking the adapter sequences and replaced 'illumina' with defined adapter sequences a lot of miRNA reads were indentified.

**Comment by mhalushka** [comment]
I'm glad to hear it's working.  It sound like you weren't using an illumina kit.  The illumina adaptor sequence is TGGAATTCTCGGGTGCCAAGGAACTCCAG, so if you used a different kit with a different sequence, cut adapt will not remove your sequence and miRge will not be able to find your miRNAs.
