### ISSUE TITLE
Novel miRNA detection in predict mode crashes with "substring not found" 

### ISSUE THREAD

**Issue by rjaksik** [mhalushka/miRge#23]
Hi, I was able to successfully analyze over 50 samples from my experiment however one of them crashes on the novel miRNA detection step:

> miRge2.0 predict -s SAMPLE.R1.fastq.gz -d miRBase -pb /library/software/bowtie-1.2.2 -pr /library/software/RNAfold_2.0.5 -ps /library/software/samtools_1.3 -lib /library/miRge2/mirBase22 -sp human -ad AACTGTAGGCACCATC -ai -gff -di -cpu 1
> 
> Performing quantitation analysis of SAMPLE.R1.fastq...
> It takes: 683.19s
> 
> Performing annotation for all of the collasped sequences...
> All annotation cycles completed (243.41 sec).
> 
> Summarizing and tabulating results...
> The number of A-to-I editing sites for is less than 10 so that no heatmap is drawn.
> Summary Complete (130.82 sec)
> Annotation of miRge2.0 Completed (1057.42 sec)
> 
> Performing prediction of novel miRNAs...
> Start to predict
> Traceback (most recent call last):
>   File "/usr/bin/miRge2.0", line 11, in <module>
>     sys.exit(main())
>   File "/usr/lib/python2.7/site-packages/mirge/__main__.py", line 652, in main
>     write_novel_report(novelmiRNALListFile, featureFile, clusterFile, rnafoldCmdTmp)
>   File "/usr/lib/python2.7/site-packages/mirge/utils/write_novel_report.py", line 745, in write_novel_report
>     passengerReadContentlist = padClusteredList(passengerReadContentlistRaw, passengerMiRNASeq, matureMiRNAPrecusorSeq, passengerStartPos, passengerEndPos, passengerStrand)
>   File "/usr/lib/python2.7/site-packages/mirge/utils/write_novel_report.py", line 460, in padClusteredList
>     startTmp = matureMiRNAPrecusorSeq.index(matureMiRNASeq)
> ValueError: substring not found

I will be very grateful for any suggestions on how to resolve this issue.

Best regards,
Roman

**Comment by mhalushka** [comment]
Roman,
    I don't know why that happened to you.  I'll see if we can figure that out.  But if the other 49 samples work, it seems to suggest something unusual about this sample.  Is there anything unique about it?  Is it a larger file?  Is it the smallest file?  Is there a chance there are no novel miRNAs to be found in it?  I'm just trying to think of reasons why this might have failed.

**Comment by rjaksik** [comment]
Its neither the smallest or the largest file, the size is actually very close to the average in this set. The file is not truncated and doesn’t seem to contain corrupted reads, It also doesn’t stand out in QC. Quantitation analysis for that sample looks ok. 

This is actually one of 3 control samples which we add to each batch so in total I have 3 technical replicates for it. In the first and second batch I got 8 and 12 novel miRNAs respectively, with only one overlap. I have no reasons to assume that there should be novel miRNAs, however the alternative seems unlikely considering the replicates, which have similar coverage. 

I can send you that file through our webserver, its only 1.4GB.

**Comment by mhalushka** [comment]
Thanks.  That is bizarre.  Don't send it to me yet, but we might have to look at it eventually.  For now, we're checking the code to see why it's giving that error.  Sorry about this.

**Comment by rjaksik** [comment]
No problem. Thank you for your time, I really appreciate it.

**Comment by rjaksik** [comment]
Hi, were you able to find anything?

**Comment by mhalushka** [comment]
Still working on it.  One question, though.  Did you run that sample in annotate mode?  If so, did it process correctly there or did it also crash?  Thank you.

**Comment by rjaksik** [comment]
Yes, annotation mode works fine on that sample.

**Comment by mhalushka** [comment]
Ok.  This really seems like a bug in our software.

**Comment by arunhpatil** [comment]
Hi roman, I am looking at the code to find the bug, can you please share the sample FASTQ file which crashed during the run and one which predicted 12 novle miRNAs. 

PS: I will be joining Dr. Marc Lalushka's lab as PDF soon. 

Thanks,
Arun.

**Comment by rjaksik** [comment]
Hi Arun, I have send you the links using your gmail adress.
Thank you for your help.

**Comment by arunhpatil** [comment]
Hi Roman, I have received the links, I will get back to you soon.
