### ISSUE TITLE
Error trimming files using option: -ad ion

### ISSUE THREAD

**Issue by maikelcolli** [mhalushka/miRge#25]
When I am trying to trim .fastq files from ion torrent sequencing I am getting the error msg below:

Traceback (most recent call last):
  File "/home/maikel/.local/bin/miRge2.0", line 10, in <module>
    sys.exit(main())
  File "/home/maikel/.local/lib/python2.7/site-packages/mirge/__main__.py", line 358, in main
    phred, processed_count, kept_count = trim_file(samplePrefix, adapter, cleanedReads, int(numCPU))
  File "/home/maikel/.local/lib/python2.7/site-packages/mirge/utils/trim_file.py", line 109, in trim_file
    start_workers()
  File "/home/maikel/.local/lib/python2.7/site-packages/mirge/utils/trim_file.py", line 96, in start_workers
    worker = Worker(queue=read_queue, results=result_queue, phred64=phred==64, adapter=adapter)
  File "/home/maikel/.local/lib/python2.7/site-packages/mirge/utils/trim_file.py", line 39, in __init__
    self.adapters = parse_adapters(adapter, error_rate=self.error_rate)
  File "/home/maikel/.local/lib/python2.7/site-packages/mirge/utils/trim_file.py", line 22, in parse_adapters
    return AdapterParser(max_error_rate=error_rate).parse_multi(adapter.split(','), [], [])
  File "/home/maikel/.local/lib/python2.7/site-packages/cutadapt/adapters.py", line 194, in parse_multi
    adapters.extend(self.parse(spec, cmdline_type))
  File "/home/maikel/.local/lib/python2.7/site-packages/cutadapt/adapters.py", line 168, in parse
    yield self._parse_no_file(spec, name, cmdline_type)
  File "/home/maikel/.local/lib/python2.7/site-packages/cutadapt/adapters.py", line 150, in _parse_no_file
    return self.adapter_class(sequence=spec, where=where, name=name, **self.constructor_args)
  File "/home/maikel/.local/lib/python2.7/site-packages/cutadapt/adapters.py", line 482, in __init__
    'XACGTURYSWKMBDHVN.'.format(c, self.sequence))
ValueError: Character '1' in adapter sequence '11' is not a valid IUPAC code. Use only characters XACGTURYSWKMBDHVN.

**Comment by mhalushka** [comment]
Hi.   Thanks for writing.  We think your data has numbers in it and miRge can only use the standard nucleotide letters.  Can you check your FASTQ file?  If so, you'll need to convert this before processing in miRge.
