### ISSUE TITLE
mirbase id not being found

### ISSUE THREAD

**Issue by chelseaherdman** [mhalushka/miRge#27]
Hi,

I am successfully able to run mirge2.0 using mirgenedb but not mirbase database. I downloaded the zebrafish libraries on March 2nd so I believe everything is up to date. When I try running the following code I get an error but the run finishes successfully if I use "-d MirGeneDB".

```
/opt/anaconda/anaconda2/bin/miRge2.0 annotate \
-s ../../processed_fastq_unzip/14806X10.fastq \
-d miRBase \
-o 14806X10 \
-pb /usr/local/bowtie-1.1.1/ \
-lib ../mirge_libs_20200302/ \
-sp zebrafish \
-ai \
-gff \
-cpu 8  > 14806X10/log.txt 2>&1
```
Here is the output in the log.txt file:
```
Performing quantitation analysis of 14806X10_INSERT_180223_D00294_0376_ACBYHRANXX_S51_L008_R1_001.fastq...
It takes: 226.86s

Performing annotation for all of the collasped sequences...
Traceback (most recent call last):
  File "/opt/anaconda/anaconda2/bin/miRge2.0", line 11, in <module>
    load_entry_point('mirge==2.0', 'console_scripts', 'miRge2.0')()
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/mirge/__main__.py", line 266, in main
    runAnnotationPipeline(bowtieBinary, seqDic, numCPU, phred64, annotNameList, outputdir, logDic, mirna_index, hairpin_index, mature_tRNA_index, pre_tRNA_index, snoRNA_index, rRNA_index, ncrna_others_index, mrna_index, spikeIn, spikeIn_index, gff_output, miRNamePreNameDic, isomiRContentDic, miRNA_database)
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/mirge/utils/runAnnotationPipeline.py", line 516, in runAnnotationPipeline
    updateIsomiRDic2(isomiRContentDic, hairpinNameSeqDic, mirnaLibNameSeqDic, i, miRNamePreNameDic, miRNA_database)
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/mirge/utils/runAnnotationPipeline.py", line 380, in updateIsomiRDic2
    preMiRSeq = hairpinNameSeqDic[isomiRContentDic[seqKey]['preMiRName']]
KeyError: 'dre-mir-139-3p'
log.txt (END)
```
The exact same error occurs for all of my 44 input files.

Thank you,

Chelsea

**Comment by arunhpatil** [comment]
Hello, 

Sorry to hear about this missing id. Can you re-run a sample without `-gff` option. I suspect that this is due to the missing key ID (dre-mir-139-3p) while reporting GFF format. If this is the case, we will update the script in our new release soon.  

Thanks,
Arun

**Comment by chelseaherdman** [comment]
That worked, thanks!
