### ISSUE TITLE
Library file names not as expected for zebrafish

### ISSUE THREAD

**Issue by bdemarest** [mhalushka/miRge#7]
It looks like several of the zebrafish library files have names that do not match what is expected by miRge2.0. 

I'm wondering if you have any suggestions for the easiest way to correct this. 

I've tried manually renaming a few files, but that seems likely to cause errors or other problems later. I also took a quick look at the bowtie_build.py page, but there it's not clear to me how to run the scripts, nor what input files are required for zebrafish.

```
Traceback (most recent call last):
  File "/opt/anaconda/anaconda2/bin/miRge2.0", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/mirge/__main__.py", line 115, in main
    with open(mergeLibFile, 'r') as inf:
IOError: [Errno 2] No such file or directory: './zebrafish/zebrafish/annotation.Libs/zebrafish_merges_miRBase.csv'


Traceback (most recent call last):
  File "/opt/anaconda/anaconda2/bin/miRge2.0", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/mirge/__main__.py", line 151, in main
    miRNamePreNameDic = extractPreMiRName(miRNA_coordinate, miRNA_database)
  File "/opt/anaconda/anaconda2/lib/python2.7/site-packages/mirge/utils/extractPreMiRName.py", line 26, in extractPreMiRName
    with open(miRNA_coordinate, 'r') as inf:
IOError: [Errno 2] No such file or directory: './mirge_libs/zebrafish/annotation.Libs/zebrafish_miRBase.gff3'


The bowtie index file of zebrafish_mature_trna.*.ebwt is not located at ./mirge_libs/zebrafish/index.Libs, please check it.
```

**Comment by luketerry** [comment]
@bdemarest We also updated mirge on 05/11/2018, So please reinstall the newest one (v2.0.3) via conda.

**Comment by bdemarest** [comment]
Thank you. Downloading the updated libraries resolved the error.
