### ISSUE TITLE
compressed fastq as input 

### ISSUE THREAD

**Issue by dulveling** [mhalushka/miRge#9]
Hi,
thanks for the software, it's very usefull
I would have liked to know if there is a way to read fastq compressed to software or to add this feature?

Thanks

**Comment by mhalushka** [comment]
Thanks for writing. It's something we had in an earlier version of miRge and are looking to see how feasible it is to put it into miRge 2.0.

**Comment by luketerry** [comment]
@dulveling  Thank you for your suggestion. We have added the function so that miRge2.0 can support *.fastq.gz files as input. The source code in Githib is updated and the new version "mirge 2.0.4" will be available in bioconda soon.

**Comment by dulveling** [comment]
Hi
thanks for your reply,
I was able to install the latest version miRge2.0.4 which includes the feature (with conda)
I updated the resource files via the provided wget (for the mouse) 

Nevertheless, I now have an error that had never appeared before

```Traceback (most recent call last):
  File "/home/damien.ulveling/Softwares/miniconda2/envs/miRNA/bin/miRge2.0", line 11, in <module>
    load_entry_point('mirge==2.0', 'console_scripts', 'miRge2.0')()
  File "/home/damien.ulveling/Softwares/miniconda2/envs/miRNA/lib/python2.7/site-packages/mirge/__main__.py", line 274, in main
    runAnnotationPipeline(bowtieBinary, seqDic, numCPU, phred64, annotNameList, outputdir, logDic, mirna_index, hairpin_index, mature_tRNA_index, pre_tRNA_index, snoRNA_index, rRNA_index, ncrna_others_index, mrna_index, spikeIn, spikeIn_index, gff_output, miRNamePreNameDic, isomiRContentDic, miRNA_database)
  File "/home/damien.ulveling/Softwares/miniconda2/envs/miRNA/lib/python2.7/site-packages/mirge/utils/runAnnotationPipeline.py", line 516, in runAnnotationPipeline
    updateIsomiRDic2(isomiRContentDic, hairpinNameSeqDic, mirnaLibNameSeqDic, i, miRNamePreNameDic, miRNA_database)
  File "/home/damien.ulveling/Softwares/miniconda2/envs/miRNA/lib/python2.7/site-packages/mirge/utils/runAnnotationPipeline.py", line 380, in updateIsomiRDic2
    preMiRSeq = hairpinNameSeqDic[isomiRContentDic[seqKey]['preMiRName']]
KeyError: 'mmu-mir-712-5p'
```
the command launched being:
```miRge2.0 annotate -s input.fastq.gz -d miRBase -pb /home/damien.ulveling/Softwares/miniconda2/bin/ -lib /mnt/hdd/db/MM/mm10/miRge2.0 -sp mouse -ai -gff -cpu 24 -o miRge2/folder_out 2> logs/miRge2/miRge2.log```

**Comment by luketerry** [comment]
@dulveling Thank you for your report. 
After debugging the code, I think this error is caused by the wrongly inferred pre miRNA name of mmu-miR-712-5p. As far as I know, mmu-miR-712-5p doesn't have genomic coordinate information, so it's not recorded in the corresponding *.gff3 file and will be used to inferred its pre miRNA name. This kind of name mapping problem happens rarely. I just fixed this bug in the file of runAnnotationPipeline.py. The revised file is updated in Github.
Because I'm not 100% sure whether it can solve your issue (I haven't submitted the new mirge verision to bioconda yet). I recommend you to uninstall your current mirge and reinstall the updated miRge using pip by running "python setup.py bdist_wheel" and "pip install ./dist/mirge-2.0-py2-none-any.whl".  Hopefully, this can solve your problem. Please let me know whether it can work and I will decide to update mirge in bioconda as well.
Thank you.

**Comment by dulveling** [comment]
@luketerry Thank you for your quick action.
Everything goes as planned now

I would like to ask you on another point like the consideration of the umi.
Would it be possible to obtain intermediate BAM (option??) or customize the command of the counting part? The umi info is in the read names.

Thanks again for your follow-up and your help

**Comment by luketerry** [comment]
@dulveling I'm sorry that UMI is not supported in miRge2.0. As far as I know, UMIs are widely used in single-cell RNA- seq. For small RNA seq, It can use UMI to tag each mirRNA to eliminate PCR and sequencing bias, but UMIs are not that that widely applied. So we don't have this function right now.
